AWSTemplateFormatVersion: "2010-09-09"
Description: "CloudFormation IaC --- A public (accessible from internet) and a private (accessible only via VPN) Subnet"

################################################################################
#
# Decision Trees: none
#
################################################################################


################################################################################
#
# Metadata (optional)
# provide details about template
#
# See: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/metadata-section-structure.html
#
################################################################################

Metadata:
 AWS::CloudFormation::Interface:
  ParameterGroups:
  - Label:
    default: "Naming details"
   Parameters:
   - Desig
   - TopStack
  - Label:
    default: "Subnet configuration"
   Parameters:
   - AvailabilityZone
   - IgwRouteTable
   - InternetAccess
   - PrivateSubnetCidr
   - PublicSubnetCidr
   - Vpc


################################################################################
#
# Parameters (optional)
# Passes values into templates when creating a stack
#
# See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/parameters-section-structure.html
#
################################################################################

Parameters:
 #=======================================
 # Naming details
 #=======================================

 Desig:
  Description: "A string used to tell resources created by different instances this stack apart (for example its purpose or just a number)."
  Type: String

 TopStack:
  Description: " name top-level Stack this Stack, if nested, ultimately belongs to (this Stacks name else; examples: \"prod\" or \"nonprod\")."
  Type: String

 #=======================================
 # Subnet configuration
 #=======================================

 AvailabilityZone:
  Description: "AvailabilityZone subnets created in."
  Type: AWS::EC2::AvailabilityZone::Name

 IgwRouteTable:
  Description: " ID a RouteTable contains Routes to Internet Gateway."
  Type: String

 InternetAccess:
  Description: "Indicates wher internet access should be possible for Instances in private subnets."
  Type: String
  AllowedValues: [ "disabled", "enabled" ]
  Default: "enabled"

 PrivateSubnetCidr:
  Description: "Private Subnet IP class (must be a valid subclass VPC, e.g. 10.31.1.0/24)."
  Type: String
  AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
  ConstraintDescription: "Must be a valid CIDR range in form x.x.x.x AND a subnet VPC IP Class."

 PublicSubnetCidr:
  Description: "Public Subnet IP class (must be a valid subclass VPC, e.g. 10.31.0.0/24)."
  Type: String
  AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
  ConstraintDescription: "Must be a valid CIDR range in form x.x.x.x AND a subnet VPC IP Class."

 Vpc:
  Description: "ID VPC will host subnets."
  Type: AWS::EC2::VPC::Id


################################################################################
#
# Conditions (optional)
# Includes statements define when a resource is created or when a property is defined
#
# See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/conditions-section-structure.html
#
################################################################################

Conditions:
 # If access to internet should be disabled, we should do this
 EnableInternetAccess: !Equals [ !Ref InternetAccess, "enabled" ]


################################################################################
#
# Resources (required)
# Declares AWS resources you want to include in stack
#
# See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
#
################################################################################

Resources:
 #----------------------------
 # Private Subnet
 #----------------------------

 # Routing private subnet
 PrivateRouteTable:
  Type: AWS::EC2::RouteTable
  Properties:
   Vpc_Id: !Ref Vpc
   Tags:
   - Key: "Name"
    Value: !Sub "${TopStack}-rt-private-${Desig}"

 # This private subnet should contain most resources. Especially security critical ones.
 # Components in this subnet can only "dial out" via NAT Gateway but are not by default not reachable form WWW
 PrivateSubnet:
  Type: AWS::EC2::Subnet
  Properties:
   AvailabilityZone: !Ref AvailabilityZone
   CidrBlock: !Ref PrivateSubnetCidr
   MapPublicIpOnLaunch: true
   Tags:
   - Key: "Name"
    Value: !Sub "${TopStack}-sn-private-${Desig}"
   Vpc_Id: !Ref Vpc

 # Connecting private route table with private subnet
 PrivateSubnetPrivateRouteTableAssociation:
  Type: AWS::EC2::SubnetRouteTableAssociation
  Properties:
   RouteTableId: !Ref PrivateRouteTable
   SubnetId: !Ref PrivateSubnet

 #----------------------------
 # Public Subnet
 #----------------------------

 # Each NAT Gateway needs a Elastic IP to be reachable from WWW.
 PublicEip:
  Type: AWS::EC2::EIP
  Properties:
   Domain: "vpc"
   Tags:
   - Key: "Name"
    Value: !Sub "${TopStack}-eip-natgw-public"

 # Gateway acts as an adapter between private Resources (e.g. AEM-VMs) and WWW (e.g. repositories, external data, etc.)
 PublicNatGateway:
  Condition: EnableInternetAccess
  Type: AWS::EC2::NatGateway
  Properties:
   AllocationId: !GetAtt PublicEip.AllocationId
   SubnetId: !Ref PublicSubnet
   Tags:
   - Key: "Name"
    Value: !Sub "${TopStack}-natgw-public-${Desig}"

 # Route to let instances in PrivateSubnet access internet via PublicNatGateway.
 PublicNatGatewayRoute:
  Condition: EnableInternetAccess
  Type: AWS::EC2::Route
  Properties:
   DestinationCidrBlock: "0.0.0.0/0"
   NatGatewayId: !Ref PublicNatGateway
   RouteTableId: !Ref PrivateRouteTable

 # This Subnet accessible from internet. All resources need to be public must be located here.
 PublicSubnet:
  Type: AWS::EC2::Subnet
  Properties:
   AvailabilityZone: !Ref AvailabilityZone
   CidrBlock: !Ref PublicSubnetCidr
   MapPublicIpOnLaunch: true
   Tags:
   - Key: "Name"
    Value: !Sub "${TopStack}-sn-public-${Desig}"
   Vpc_Id: !Ref Vpc

 # Connecting internet gateway route table with public subnet
 PublicSubnetPublicRouteTableAssociation:
  Type: AWS::EC2::SubnetRouteTableAssociation
  Properties:
   RouteTableId: !Ref IgwRouteTable
   SubnetId: !Ref PublicSubnet


################################################################################
#
# Outputs (optional)
# Declares output values you can import into or stacks (to create cross-stack references)
#
# See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/outputs-section-structure.html
#
################################################################################

Outputs:

 PrivateRouteTable:
  Description: " ID Route Table associated with private subnet."
  Value: !Ref PrivateRouteTable

 PrivateSubnet:
  Description: " ID private subnet."
  Value: !Ref PrivateSubnet

 PublicSubnet:
  Description: " ID public subnet."
  Value: !Ref PublicSubnet

 AvailabilityZone:
  Description: " Name Availability Zone subnets have been created in."
  Value: !Ref AvailabilityZone
