---
AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Provision AWS Managed Active Directory
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Active Directory Settings
      Parameters:
      - pDomainName
      - pMicrosoftADShortName
      - pMicrosoftADPW
      - pEdition
      - pCreateAlias
      - pEnableSingleSignOn
    - Label:
        default: VPC Networking Settings
      Parameters:
      - pVpc_Id
      - pPrivateSubnet1
      - pPrivateSubnet2
    ParameterLabels:
      pDomainName:
        default: Name
      pMicrosoftADShortName:
        default: Short Name
      pMicrosoftADPW:
        default: Active Directory Admin Password
      pEdition:
        default: Edition
      pCreateAlias:
        default: Create Alias
      pEnableSingleSignOn:
        default: Enable Single Sign On
      pVpc_Id:
        default: VPC ID
      pPrivateSubnet1:
        default: Private Subnet 1
      pPrivateSubnet2:
        default: Private Subnet 2

Parameters:
  pEdition:
    Description: >
       AWS Microsoft AD edition. Valid values include Standard and
      Enterprise.  default is Enterprise.
    Type: String
    Default: Enterprise
    AllowedValues:
    - Standard
    - Enterprise
  pDomainName:
    Description: >
       fully qualified name for  Microsoft Active Directory
      in AWS, such as corp.example.com.  name doesn't need to be
      publicly resolvable; it will resolve inside your VPC only.
    Type: String
    Default: corp.example.com
  pMicrosoftADShortName:
    Description: >
       NetBIOS name for your domain, such as CORP. If you don't specify
      a value, AWS Directory Service uses  first part your directory
      DNS server name. For example, if your directory DNS server name is
      corp.example.com, AWS Directory Service specifies CORP for  NetBIOS
      name.
    Type: String
    Default: corp
  pEnableSingleSignOn:
    Description: >
      Wher to enable single sign-on for a Microsoft Active
      Directory in AWS. Single sign-on allows users in your
      directory to access certain AWS services from a computer
      joined to  directory without having to enter ir
      credentials separately. If you don't specify a value,
      AWS CloudFormation disables single sign-on by default.
      If enabling SSO, n "Create Alias" need to be set to true.
    Type: String
    AllowedValues:
    - 'true'
    - 'false'
    Default: 'false'
  pCreateAlias:
    Description: >
      A unique alias to assign to  Microsoft Active Directory in AWS.
      AWS Directory Service uses  alias to construct  access URL for
       directory, such as http://alias.awsapps.com. By default, AWS
      CloudFormation does not create an alias.
    Type: String
    AllowedValues:
    - 'true'
    - 'false'
    Default: 'false'
  pMicrosoftADPW:
    Description: >
       password for  default administrative user, Admin.
    Type: String
    NoEcho: true
    Default: Pass@w0rd
  pPrivateSubnet1:
    Description: >
      A subnet within  selected VPC. Each subnet must be in
      different Availability Zones (AZs). AWS Directory Service
      creates a directory server and a DNS server in each subnet.
    Type: AWS::EC2::Subnet::Id
  pPrivateSubnet2:
    Description: >
      A second subnet in same VPC is in different AZ.
      Each subnet must be in different Availability Zones (AZs).
      AWS Directory Service creates a directory server and a DNS
      server in each subnet.
    Type: AWS::EC2::Subnet::Id
  pVpc_Id:
    Description: >
       VPC ID in which to create  Microsoft Active Directory server.
    Type: AWS::EC2::VPC::Id

Conditions:
  cAlias: !Equals [ !Ref pCreateAlias, 'true' ]

Resources:
  rMSDirectory:
    Type: AWS::DirectoryService::MicrosoftAD
    Properties:
      CreateAlias: !Ref pCreateAlias
      Edition: !Ref pEdition
      EnableSso: !Ref pEnableSingleSignOn
      Name: !Ref pDomainName
      Password: !Ref pMicrosoftADPW
      ShortName: !Ref pMicrosoftADShortName
      VpcSettings:
        SubnetIds:
        - !Ref pPrivateSubnet1
        - !Ref pPrivateSubnet2
        Vpc_Id: !Ref pVpc_Id

Outputs:
  DirectoryID:
    Description: ID  MS Directory
    Value: !Ref rMSDirectory
  PrimaryDNS:
    Description: DNS IPs  MS Directory
    Value: !Select [ '0', !GetAtt rMSDirectory.DnsIpAddresses ]
  SecondaryDNS:
    Description: DNS IPs  MSDirectory
    Value: !Select [ '1', !GetAtt rMSDirectory.DnsIpAddresses ]
  DirectoryAlias:
    Description: URL for  alias
    Condition: cAlias
    Value: !GetAtt rMSDirectory.Alias
